name: PR Checks

on:
  push:
    branches: [main, master, feature/*]
  pull_request:
    branches: [main, master, feature/*]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Poetry (dependency manager)
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Step 4: Install dependencies with Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Run Black (code style linter)
      - name: Run black (lint)
        run: |
          poetry run black --check app/

      # Step 6: (Optional) Run tests if you add them later
      # - name: Run tests
      #   run: |
      #     cd app
      #     poetry run pytest 